name: Daily Blocklist Update

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true

      - name: Verify and Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run Go Optimizer
        run: go run merge.go

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add whitelist.txt blocklist.txt version.txt version.json sources.txt allowlist.txt blocklist.custom.txt
          
          if git diff --cached --quiet; then
            echo "Keine Änderungen gefunden."
          else
            git commit -m "Auto-Update: DNS List"
            git push
          fi
