name: Daily Blocklist Update

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch: 

# GLOBAL: Das gilt für ALLES in diesem File
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Wir können es auch hier für den gesamten Job erzwingen
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - name: Verify and Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run Go Optimizer
        run: go run merge.go

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add whitelist.txt blocklist.txt version.txt version.json sources.txt allowlist.txt
          
          if git diff --cached --quiet; then
            echo "Keine Änderungen gefunden."
          else
            git commit -m "Auto-Update: DNS List (Node24 Sync)"
            git push
          fi